version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: nha-hang-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my-network

  client-app:
    build: .
    container_name: nha-hang-app
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASS: 123456
    networks:
      - my-network
    stdin_open: true
    tty: true

volumes:
  db_data:

networks:
  my-network:
